server:
  port: 9070


spring:
  sql:
    init:
      mode: always
  datasource: # jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/genie?characterEncoding=utf-8
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  servlet: #fileupload
    multipart:
      max-file-size: 20MB
      enabled: true

mybatis:
  type-aliases-package: com.genie.myapp.dto
  mapper-locations: mapper/*Mapper.xml

logging.level:
  root: info
  org.hibernate.SQL: debug



